In [31]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
data = pd.read_csv("student-maths-performance.csv")

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [34]:
data.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [35]:
data.tail()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
390,MS,M,20,U,LE3,A,2,2,services,services,...,5,5,4,4,5,4,11,9,9,9
391,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,3,14,16,16
392,MS,M,21,R,GT3,T,1,1,other,other,...,5,5,3,3,3,3,3,10,8,7
393,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,0,11,12,10
394,MS,M,19,U,LE3,T,1,1,other,at_home,...,3,2,3,3,3,5,5,8,9,9

In [36]:
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

In [40]:
print(y[0:10])

[ 6  6 10 15 10 15 11  6 19 15]

In [43]:
print(X[0:10, :])

[['F' 18 'U' 'GT3' 'A' 4 4 'at_home' 'teacher' 'course' 'mother' 2 2 0
  'yes' 'no' 'no' 'no' 'yes' 'yes' 'no' 'no' 4 3 4 1 1 3 6 5 6]
 ['F' 17 'U' 'GT3' 'T' 1 1 'at_home' 'other' 'course' 'father' 1 2 0 'no'
  'yes' 'no' 'no' 'no' 'yes' 'yes' 'no' 5 3 3 1 1 3 4 5 5]
 ['F' 15 'U' 'LE3' 'T' 1 1 'at_home' 'other' 'other' 'mother' 1 2 3 'yes'
  'no' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 4 3 2 2 3 3 10 7 8]
 ['F' 15 'U' 'GT3' 'T' 4 2 'health' 'services' 'home' 'mother' 1 3 0 'no'
  'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 3 2 2 1 1 5 2 15 14]
 ['F' 16 'U' 'GT3' 'T' 3 3 'other' 'other' 'home' 'father' 1 2 0 'no'
  'yes' 'yes' 'no' 'yes' 'yes' 'no' 'no' 4 3 2 1 2 5 4 6 10]
 ['M' 16 'U' 'LE3' 'T' 4 3 'services' 'other' 'reputation' 'mother' 1 2 0
  'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 5 4 2 1 2 5 10 15 15]
 ['M' 16 'U' 'LE3' 'T' 2 2 'other' 'other' 'home' 'mother' 1 2 0 'no'
  'no' 'no' 'no' 'yes' 'yes' 'yes' 'no' 4 4 4 1 1 3 0 12 12]
 ['F' 17 'U' 'GT3' 'A' 4 4 'other' 'teacher' 'home' 'mother' 2 2 0 'yes'
  'yes' 'no' 'no' 'yes' 'yes' 'no' 'no' 4 1 4 1 1 1 6 6 5]
 ['M' 15 'U' 'LE3' 'A' 3 2 'services' 'other' 'home' 'mother' 1 2 0 'no'
  'yes' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 4 2 2 1 1 1 0 16 18]
 ['M' 15 'U' 'GT3' 'T' 3 4 'other' 'other' 'home' 'mother' 1 2 0 'no'
  'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 5 5 1 1 1 5 0 14 15]]

In [52]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder()

# Encode the "sex" column
X[:, :1] = np.array(encoder.fit_transform(X[:, :1]))

# Encode the "address" column
X[:, 2:3] = np.array(encoder.fit_transform(X[:, 2:3]))

# Encode the "famsize" column
X[:, 3:4] = np.array(encoder.fit_transform(X[:, 3:4]))

# Encode the "pstatus" column
X[:, 4:5] = np.array(encoder.fit_transform(X[:, 4:5]))

# Encode the "Mjob" and "Fjob" column
X[:, 7:11] = np.array(encoder.fit_transform(X[:, 7:11]))

# Encode the  column
X[:, 14:22] = np.array(encoder.fit_transform(X[:, 14:22]))

In [53]:
print(X[0:10])

[[0.0 18 1.0 0.0 0.0 4 4 0.0 4.0 0.0 1.0 2 2 0 1.0 0.0 0.0 0.0 1.0 1.0
  0.0 0.0 4 3 4 1 1 3 6 5 6]
 [0.0 17 1.0 0.0 1.0 1 1 0.0 2.0 0.0 0.0 1 2 0 0.0 1.0 0.0 0.0 0.0 1.0
  1.0 0.0 5 3 3 1 1 3 4 5 5]
 [0.0 15 1.0 1.0 1.0 1 1 0.0 2.0 2.0 1.0 1 2 3 1.0 0.0 1.0 0.0 1.0 1.0
  1.0 0.0 4 3 2 2 3 3 10 7 8]
 [0.0 15 1.0 0.0 1.0 4 2 1.0 3.0 1.0 1.0 1 3 0 0.0 1.0 1.0 1.0 1.0 1.0
  1.0 1.0 3 2 2 1 1 5 2 15 14]
 [0.0 16 1.0 0.0 1.0 3 3 2.0 2.0 1.0 0.0 1 2 0 0.0 1.0 1.0 0.0 1.0 1.0
  0.0 0.0 4 3 2 1 2 5 4 6 10]
 [1.0 16 1.0 1.0 1.0 4 3 3.0 2.0 3.0 1.0 1 2 0 0.0 1.0 1.0 1.0 1.0 1.0
  1.0 0.0 5 4 2 1 2 5 10 15 15]
 [1.0 16 1.0 1.0 1.0 2 2 2.0 2.0 1.0 1.0 1 2 0 0.0 0.0 0.0 0.0 1.0 1.0
  1.0 0.0 4 4 4 1 1 3 0 12 12]
 [0.0 17 1.0 0.0 0.0 4 4 2.0 4.0 1.0 1.0 2 2 0 1.0 1.0 0.0 0.0 1.0 1.0
  0.0 0.0 4 1 4 1 1 1 6 6 5]
 [1.0 15 1.0 1.0 0.0 3 2 3.0 2.0 1.0 1.0 1 2 0 0.0 1.0 1.0 0.0 1.0 1.0
  1.0 0.0 4 2 2 1 1 1 0 16 18]
 [1.0 15 1.0 0.0 1.0 3 4 2.0 2.0 1.0 1.0 1 2 0 0.0 1.0 1.0 1.0 1.0 1.0
  1.0 0.0 5 5 1 1 1 5 0 14 15]]

In [55]:
print(X[0:20, :])

[[0.0 18 1.0 0.0 0.0 4 4 0.0 4.0 0.0 1.0 2 2 0 1.0 0.0 0.0 0.0 1.0 1.0
  0.0 0.0 4 3 4 1 1 3 6 5 6]
 [0.0 17 1.0 0.0 1.0 1 1 0.0 2.0 0.0 0.0 1 2 0 0.0 1.0 0.0 0.0 0.0 1.0
  1.0 0.0 5 3 3 1 1 3 4 5 5]
 [0.0 15 1.0 1.0 1.0 1 1 0.0 2.0 2.0 1.0 1 2 3 1.0 0.0 1.0 0.0 1.0 1.0
  1.0 0.0 4 3 2 2 3 3 10 7 8]
 [0.0 15 1.0 0.0 1.0 4 2 1.0 3.0 1.0 1.0 1 3 0 0.0 1.0 1.0 1.0 1.0 1.0
  1.0 1.0 3 2 2 1 1 5 2 15 14]
 [0.0 16 1.0 0.0 1.0 3 3 2.0 2.0 1.0 0.0 1 2 0 0.0 1.0 1.0 0.0 1.0 1.0
  0.0 0.0 4 3 2 1 2 5 4 6 10]
 [1.0 16 1.0 1.0 1.0 4 3 3.0 2.0 3.0 1.0 1 2 0 0.0 1.0 1.0 1.0 1.0 1.0
  1.0 0.0 5 4 2 1 2 5 10 15 15]
 [1.0 16 1.0 1.0 1.0 2 2 2.0 2.0 1.0 1.0 1 2 0 0.0 0.0 0.0 0.0 1.0 1.0
  1.0 0.0 4 4 4 1 1 3 0 12 12]
 [0.0 17 1.0 0.0 0.0 4 4 2.0 4.0 1.0 1.0 2 2 0 1.0 1.0 0.0 0.0 1.0 1.0
  0.0 0.0 4 1 4 1 1 1 6 6 5]
 [1.0 15 1.0 1.0 0.0 3 2 3.0 2.0 1.0 1.0 1 2 0 0.0 1.0 1.0 0.0 1.0 1.0
  1.0 0.0 4 2 2 1 1 1 0 16 18]
 [1.0 15 1.0 0.0 1.0 3 4 2.0 2.0 1.0 1.0 1 2 0 0.0 1.0 1.0 1.0 1.0 1.0
  1.0 0.0 5 5 1 1 1 5 0 14 15]
 [0.0 15 1.0 0.0 1.0 4 4 4.0 1.0 3.0 1.0 1 2 0 0.0 1.0 1.0 0.0 1.0 1.0
  1.0 0.0 3 3 3 1 2 2 0 10 8]
 [0.0 15 1.0 0.0 1.0 2 1 3.0 2.0 3.0 0.0 3 3 0 0.0 1.0 0.0 1.0 1.0 1.0
  1.0 0.0 5 2 2 1 1 4 4 10 12]
 [1.0 15 1.0 1.0 1.0 4 4 1.0 3.0 0.0 0.0 1 1 0 0.0 1.0 1.0 1.0 1.0 1.0
  1.0 0.0 4 3 3 1 3 5 2 14 14]
 [1.0 15 1.0 0.0 1.0 4 3 4.0 2.0 0.0 1.0 2 2 0 0.0 1.0 1.0 0.0 1.0 1.0
  1.0 0.0 5 4 3 1 2 3 2 10 10]
 [1.0 15 1.0 0.0 0.0 2 2 2.0 2.0 1.0 2.0 1 3 0 0.0 1.0 0.0 0.0 1.0 1.0
  1.0 1.0 4 5 2 1 1 3 0 14 16]
 [0.0 16 1.0 0.0 1.0 4 4 1.0 2.0 1.0 1.0 1 1 0 0.0 1.0 0.0 0.0 1.0 1.0
  1.0 0.0 4 4 4 1 2 2 4 14 14]
 [0.0 16 1.0 0.0 1.0 4 4 3.0 3.0 3.0 1.0 1 3 0 0.0 1.0 1.0 1.0 1.0 1.0
  1.0 0.0 3 2 3 1 2 2 6 13 14]
 [0.0 16 1.0 0.0 1.0 3 3 2.0 2.0 3.0 1.0 3 2 0 1.0 1.0 0.0 1.0 1.0 1.0
  0.0 0.0 5 3 2 1 1 4 4 8 10]
 [1.0 17 1.0 0.0 1.0 3 2 3.0 3.0 0.0 1.0 1 1 3 0.0 1.0 0.0 1.0 1.0 1.0
  1.0 0.0 5 5 5 2 4 5 16 6 5]
 [1.0 16 1.0 1.0 1.0 4 3 1.0 2.0 1.0 0.0 1 1 0 0.0 0.0 1.0 1.0 1.0 1.0
  1.0 0.0 3 1 3 1 3 5 4 8 10]]

In [93]:
df = {
    "sex": X[:, 0:1].reshape(-1),
    "age": X[:, 1:2].reshape(-1),
    "address": X[:, 2:3].reshape(-1),
    "score": X[:, -1].reshape(-1)
}

In [94]:
frame = pd.DataFrame(df)

In [95]:
print(frame)

     sex age address score
0    0.0  18     1.0     6
1    0.0  17     1.0     5
2    0.0  15     1.0     8
3    0.0  15     1.0    14
4    0.0  16     1.0    10
..   ...  ..     ...   ...
390  1.0  20     1.0     9
391  1.0  17     1.0    16
392  1.0  21     0.0     8
393  1.0  18     0.0    12
394  1.0  19     1.0     9

[395 rows x 4 columns]

In [98]:
frame.corr(numeric_only=False)

              sex       age   address     score
sex      1.000000 -0.028606 -0.028504  0.091099
age     -0.028606  1.000000 -0.146722 -0.143474
address -0.028504 -0.146722  1.000000  0.126037
score    0.091099 -0.143474  0.126037  1.000000

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [57]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [58]:
y_pred = regressor.predict(X_test)

In [59]:
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)

array([[14.42980331, 14.        ],
       [10.87148648, 10.        ],
       [ 9.2247805 ,  9.        ],
       [15.37607981, 15.        ],
       [16.46785422, 16.        ],
       [12.05681736, 12.        ],
       [13.1618151 , 14.        ],
       [10.31653572, 11.        ],
       [ 7.83538105,  9.        ],
       [14.30590415, 15.        ],
       [ 7.22102356, 10.        ],
       [15.44708081, 11.        ],
       [11.14742555, 10.        ],
       [ 8.59873137,  8.        ],
       [15.22561935, 15.        ],
       [14.78846231, 14.        ],
       [12.95504256, 12.        ],
       [ 8.37011434,  0.        ],
       [ 9.28534711, 10.        ],
       [15.08762702, 16.        ],
       [ 6.63687967,  0.        ],
       [ 2.56817812,  0.        ],
       [ 6.17481612,  8.        ],
       [14.65648683, 16.        ],
       [11.8825047 , 12.        ],
       [15.79188978, 15.        ],
       [ 9.68198868, 10.        ],
       [20.36895563, 19.        ],
       [-0.8900223 ,  0.        ],
       [13.1046026 , 14.        ],
       [-1.18787322,  0.        ],
       [ 6.61455926, 10.        ],
       [ 7.27894207,  8.        ],
       [ 5.25260843,  4.        ],
       [12.77926305, 13.        ],
       [10.68574959, 10.        ],
       [13.02149134, 13.        ],
       [18.97834279, 18.        ],
       [ 8.71176279,  8.        ],
       [11.77886181, 11.        ],
       [ 4.3655753 ,  6.        ],
       [19.32612695, 18.        ],
       [ 6.89247566,  8.        ],
       [ 8.00327486,  8.        ],
       [10.37676412, 11.        ],
       [-2.7192025 ,  0.        ],
       [11.61804506, 13.        ],
       [ 4.04055614,  0.        ],
       [11.67471093, 13.        ],
       [ 6.88278254,  7.        ],
       [ 9.07232306, 10.        ],
       [18.24186738, 18.        ],
       [12.3103427 , 10.        ],
       [ 7.2498091 ,  9.        ],
       [12.48184302, 11.        ],
       [ 8.77808837,  6.        ],
       [ 9.24958597,  9.        ],
       [12.14314488, 13.        ],
       [15.21090967, 15.        ],
       [13.81193588, 14.        ],
       [12.5930422 , 14.        ],
       [13.44404425, 15.        ],
       [13.88522802, 14.        ],
       [16.35079927, 15.        ],
       [ 7.58198753,  0.        ],
       [16.28109168, 15.        ],
       [18.18592845, 19.        ],
       [11.28058329, 12.        ],
       [ 4.86148812,  6.        ],
       [ 8.8941727 ,  9.        ],
       [ 9.83843068,  8.        ],
       [13.70026221, 15.        ],
       [ 7.12461009,  5.        ],
       [ 2.6384441 ,  0.        ],
       [12.91800652,  9.        ],
       [ 8.65715613,  0.        ],
       [10.4368967 , 11.        ],
       [17.92690147, 18.        ],
       [ 5.35858704,  0.        ]])

In [60]:
from sklearn.metrics import r2_score
r2_score(y_pred, y_test)

0.7448368823856142